## Ch11 구조체로 연관된 데이터 구조화하기

### 학습 내용
- 테스트 작성을 위한 어노테이션, 매크로 사용법
- 기본 동작과 실행 옵션, 유닛 테스트와 통합 테스트 조직화하는 방법


### 테스트 작성 방법
- 테스트란 테스트할 코드가 의도대로 기능하는지 검증하는 함수이다
- 테스트 함수의 세 가지 동작
    1. 필요한 데이터나 상태 설정
    2. 테스트할 코드 실행
    3. 의도한 결과가 나오는지 확인

### 테스트 함수 파헤치기
- 러스트에서 테스트란 test속성이 어노테이션된 함수이다
- 속성은 러스트 코드 조각에 대한 메타데이터를 의미한다
- 함수의 fn 이전 줄에 `#[test]`를 추가하면 `테스트 함수로 변경`된다
- `cargo test` 명령어로 실행되며 속성이 표시된 함수를 실행하고 결과를 보고하는 테스트 실행 바이너리를 빌드한다
- cargo로 새 라이브러리 프로젝트를 생성할 때마다 테스트 함수가 포함된 테스트 모듈이 자동 생성된다
- 테스트 모듈과 테스트 함수는 원하는 만큼 추가할 수 있다
- adder 라이브러리 프로젝트 생성
    ~~~
    cargo new adder -- lib
    cd adder
    ~~~
    - src/lib.rs 
    ~~~
    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn it_works() {
            let result = add(2, 2);
            assert_eq!(result, 4);
        }
    }
    ~~~
    - `#[test]` 어노에티션 주목
        - 이 속성은 해당 함수가 테스트 함수임을 표시하며 테스트 실행기는 이 표시를 보고 해당 함수를 테스트로 다룰 수 있다
    - `tests 모듈` 내에는 테스트 함수뿐만 아니라, 일반적인 시나리오를 설정하거나 자주 쓰이는 연산을 수행하는 일반 함수도 작성하므로, `어떤 함수가 테스트 함수인지 항상 표시해주어야 한다`
    - `assert_eq!` 매크로를 사용하여 result에 대한 단언(assert)을 했는데, 이 변수의 내용물이 2와 2를 더한 결과인 4와 같다는 것이다
    - 단언 코드는 일반적인 테스트 형식 예제로써 제공된다
    - 테스트 실행 결과
    ~~~
    cargo test
       Compiling adder v0.1.0 (/Users/byul/learning-rust/ch11/adder)
        Finished `test` profile [unoptimized + debuginfo] target(s) in 0.57s
         Running unittests src/lib.rs (target/debug/deps/adder-e11526392c9beffe)

    running 1 test
    test tests::it_works ... ok

    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

       Doc-tests adder

    running 0 tests

    test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
    ~~~
    - `running 1 test`과 생성된 테스트 함수의 이름 `it_works`와 테스트 실행 결과 `ok`가 표시된다
    - `test result: ok.`는 모든 테스트가 통과됐다는 뜻이고, `1 passed; 0 failed`는 통과하거나 실패한 테스트 개수를 종합한다
    - 어떤 테스트를 무시하도록 표시하여 특정 인스턴스에서 실행되지 않도록 할 수도 있다 (`ignored`에 표시됨)
    - cargo test에 인수를 넘겨서 어떤 문자열과 이름이 일치하는 테스트만 실행하도록 할 수도 있다 (`filtered out`에 표시됨)
    - `measured` 통계는 성능 측정 벤치마크 테스트용으로 러스트 나이틀리(nightly)에서만 사용 가능하다
        - [벤치마크 테스트 문서](https://doc.rust-lang.org/unstable-book/library-features/test.html)
    - Doc-tests adder은 문서 테스트 결과를 나타낸다 
        - 러스트는 API 문서에 작성해 놓은 예제 코드도 컴파일 할 수 있다
        - 코드와 문서 내용이 달라지지 않도록 유지보수하는 데에 유용하다   <br/><br/>
- 테스트 커스터마이징 - it_works 함수의 이름 변경
    ~~~
    #[cfg(test)]
    mod tests {
        #[test]
        fn exploration() {
            assert_eq!(2+2, 4);
        }
    }
    ~~~
    - 실행 결과
    ~~~
    cargo test
       Compiling adder v0.1.0 (/Users/byul/learning-rust/ch11/adder)
        Finished `test` profile [unoptimized + debuginfo] target(s) in 0.16s
         Running unittests src/lib.rs (target/debug/deps/adder-e11526392c9beffe)

    running 1 test
    test tests::exploration ... ok

    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

       Doc-tests adder

    running 0 tests

    test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
    ~~~
    - 출력 결과에 `it_works` 대신 `exploration`이 나타난다   <br/><br/>
- 테스트 추가하기 - another 테스트 함수
    ~~~
    #[cfg(test)]
    mod tests {
        #[test]
        fn exploration() {
            assert_eq!(2+2, 4);
        }

        #[test]
        fn another() {
            panic!("Make this test fail");
        }
    }
    ~~~
    - 실행 결과
    ~~~
    cargo test
       Compiling adder v0.1.0 (/Users/byul/learning-rust/ch11/adder)
        Finished `test` profile [unoptimized + debuginfo] target(s) in 0.20s
         Running unittests src/lib.rs (target/debug/deps/adder-e11526392c9beffe)

    running 2 tests
    test tests::exploration ... ok
    test tests::another ... FAILED

    failures:

    ---- tests::another stdout ----
    thread 'tests::another' panicked at src/lib.rs:14:9:
    Make this test fail
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


    failures:
        tests::another

    test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

    error: test failed, to rerun pass `--lib`
    ~~~
    - exploration 테스트는 통과하고 another 테스트는 실패했다는 결과가 나온다
    - 개별 결과와 요약 사이에 새로운 절 두 개가 나타난다
        - 첫번째 절은 another 테스트는 panicked 라는 이유로 실패 했으며 코드의 라인 넘버를 알려준다
        - 두 번째 절은 실패한 테스트의 이름을 목록으로 보여주어 테스트가 많아지고 테스트 실패 사유 출력량이 많아졌을 때 실패한 테스트의 이름만 실행하여 쉽게 디버깅할 수 있도록 해준다   <br/><br/>
- assert! 매크로로 결과 검사하기
    - 어떤 조건이 true임을 보장하는 테스트를 작성할 땐 표준 라이브러리가 제공하는 assert! 매크로가 유용하다
    - assert! 매크로는 부울린 값으로 평가되는 인수를 전달받는다
    - true 값이면 테스트는 통과하고 false 값이면 panic! 매크로를 호출하여 테스트를 실패하도록 만든다
    - assert! 매크로를 사용하면 작성한 코드가 의도대로 기능하는지 검사하는 데에 유용하다
    - Rectangle 구조체와 can_hold 메서드
        ~~~
        #[derive(Debug)]
        struct Rectangle {
            width: u32,
            height: u32,
        }

        impl Rectangle {
            fn can_hold(&self, other: &Rectangle) -> bool {
                self.width > other.width && self.height > other.height
            }
        }
        ~~~
    - can_hold 메서드 테스트
        ~~~
        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn larger_can_hold_smaller() {
                let larger = Rectangle {
                    width: 8,
                    height: 7,
                };
                let smaller = Rectangle {
                    width: 5,
                    height: 1,
                };

                assert!(larger.can_hold(&smaller));
            }
        }
        ~~~
        - 테스트 이름은 larger_can_hold_smaller로, Rectangle 인스턴스를 두 개 생성하고, larger.can_hold(&smaller) 호출 결과를 전달하여 assert! 매크로를 호출한다   

        - 실행 결과
        ~~~
        running 1 test
        test tests::larger_can_hold_smaller ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - smaller_cannot_hold_larger 메서드 테스트
        ~~~
        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn larger_can_hold_smaller() {
                // --생략--
            }

            #[test]
            fn smaller_cannot_hold_larger() {
                let larger = Rectangle {
                    width: 8,
                    height: 7,
                };
                let smaller = Rectangle {
                    width: 5,
                    height: 1,
                };

                assert!(!smaller.can_hold(&larger));
            }
        }
        ~~~
        - 실행 결과
        ~~~
        running 2 tests
        test tests::larger_can_hold_smaller ... ok
        test tests::smaller_cannot_hold_larger ... ok

        test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~

        - can_hold 메서드의 너비 부등호 변경
        ~~~
        impl Rectangle {
            fn can_hold(&self, other: &Rectangle) -> bool {
                self.width < other.width && self.height > other.height
            }
        }
        ~~~
        - 변경 후 실행 결과
        ~~~
        running 2 tests
        test tests::smaller_cannot_hold_larger ... ok
        test tests::larger_can_hold_smaller ... FAILED

        failures:

        ---- tests::larger_can_hold_smaller stdout ----
        thread 'tests::larger_can_hold_smaller' panicked at src/lib.rs:28:9:
        assertion failed: larger.can_hold(&smaller)
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


        failures:
            tests::larger_can_hold_smaller

        test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - larger.width는 8이고 smaller.width는 5인데 can_hold의 너비 비교 결과는 false(larger.width가 smaller.width보다 작음)를 반환한다   <br/><br/>
- assert_eq!, assert_ne! 매크로를 이용한 동등 테스트
    - 기능성 검증의 일반적인 방법은 테스트 코드의 결괏값이 예상한 값과 같은지 확인하는 것이다
    - assert_eq!, assert_ne! 매크로는 각각 두 인수를 비교하고 동등한지(equality) 그렇지 않은지(inequality) 판단한다
    - 단언 코드가 실패하면 두 값을 출력하여 테스트의 실패 사유를 더 알기 쉽게 보여준다
    - assert! 매크로는 어떤 값으로 인해 false 값이 나왔는지 출력하지 않는다   <br/><br/>
    - assert_eq! 매크로 
        ~~~
        pub fn add_two(a: i32) -> i32 {
            a + 2
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn it_add_two() {
                assert_eq!(4, add_two(2));
            }
        }
        ~~~
        - 실행 결과
        ~~~
        running 1 test
        test tests::it_add_two ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - 버그를 넣어서 실행해보기
        ~~~
        pub fn add_two(a: i32) -> i32 {
            a + 3
        }
        ~~~
        - 실행 결과
        ~~~
        running 1 test
        test tests::it_add_two ... FAILED

        failures:

        ---- tests::it_add_two stdout ----
        thread 'tests::it_add_two' panicked at src/lib.rs:24:9:
        assertion `left == right` failed
        left: 4
        right: 5
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


        failures:
            tests::it_add_two

        test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - it_add_two 테스트가 실패했고, 실패한 단언은 `assertion `left == right` failed`로 left, right의 값은 각각 4, 5 였다는 것을 메시지로 알 수 있다
        - 몇몇 프로그래밍 언어, 프레임워크에서는 동등 단언 함수의 매개변수를 expected, actual라고 지칭하며, 코드를 작성할 때 인수의 순서를 지켜야 한다
        - 러스트는 left, right로 지칭할 뿐, `예상값과 테스트 코드로 만들어진 값의 순서는 상관없다`
        - assert_ne! 매크로는 전달한 두 값이 서로 같지 않으면 통과하고, 동등하면 실패한다
        - 어떤 값이 될지는 확신할 수 없지만, `적어도 이 값은 되지 않아야 함을 알고 있는 경우에 유용하다`
        - assert_eq!,assert_ne! 매크로는 각각 ==, != 연산자를 사용한다
            - 단언에 실패할 경우 매크로는 인수를 디버그 형식으로 출력하는데 비교할 값은 PartialEq, Debug 트레이트를 구현해야 한다 
            - 직접 정의한 구조체나 열거형의 경우 PartialEq 트레이트를 구현하여 해당 타입의 값이 같음을 단언할 수 있도록 해야하고 실패 시 값이 출력될 수 있도록 Debug 트레이트도 구현해야 한다   <br/><br/>
- 커스텀 실패 메시지 추가하기
    - assert!, assert_eq!, assert_ne! 매크로에 추가 인수로 실패 메시지에 출력될 내용을 추가할 수 있다
    - 필수적인 인수들 이후의 인수는 format! 매크로로 전달된다 
    - 커스텀 메세지는 테스트 단언의 의미를 서술하는 데에 유용하며 테스트가 실패할 경우 코드의 문제점이 무엇인지 알아내기 수월하다   <br/><br/>
    - greeting 
        ~~~
        pub fn greeting(name: &str) -> String {
            format!("Hello {}", name)
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn greeting_contains_name() {
                let result = greeting("Carol");
                assert!(result.contains("Carol"));
            }
        }
        ~~~
        - 실행 결과
        ~~~
        running 1 test
        test tests::greeting_contains_name ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - 버그 케이스 실행해보기
        ~~~
        pub fn greeting(name: &str) -> String {
            format!("Hello")
        }
        ~~~
        - 실행 결과
        ~~~
        running 1 test
        test tests::greeting_contains_name ... FAILED

        failures:

        ---- tests::greeting_contains_name stdout ----
        thread 'tests::greeting_contains_name' panicked at src/lib.rs:13:9:
        assertion failed: result.contains("Carol")
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


        failures:
            tests::greeting_contains_name
        ~~~
        - 단언이 실패했다는 것과 몇 번째 줄에서 실패했는지만 표시한다   <br/><br/>
        - 포맷 문자열을 활용하여 메시지 출력하기 위한 greeting_contains_name 테스트 함수 수정
        ~~~
        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn greeting_contains_name() {
                let result = greeting("Carol");
                assert!(
                    result.contains("Carol"),
                    "Greeting did not contain name, value was `{}`",
                    result 
                );
            }
        }
        ~~~
        - 실행 결과
        ~~~
        ---- tests::greeting_contains_name stdout ----
        thread 'tests::greeting_contains_name' panicked at src/lib.rs:13:9:
        Greeting did not contain name, value was `Hello`
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        ~~~
        - 테스트 함수에 커스텀 실패 메시지를 추가하여 에러 메시지를 보고 더 많은 정보를 얻을 수 있다    <br/><br/>
- should_panic 매크로로 패닉 발생 검사하기
    - 코드의 반환값을 검사하는 것에 더하여, `예상한 대로 에러 조건을 잘 처리하는지 검사하는 것`도 중요하다
    - 패닉 검사 테스트 함수에는 should_panic 속성을 추가하여 테스트 내부에서 패닉이 발생해야 통과되고, 패닉이 발생하지 않으면 실패한다   <br/><br/>
    - Guess - panic! 발생 테스트
    ~~~
    pub struct Guess {
        value: i32,
    }

    impl Guess {
        pub fn new(value: i32) -> Guess {
            if value < 1 || value > 100 {
                panic!("Guess value must be between 1 and 100, got {}", value);
            }

            Guess {value}
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        #[should_panic]
        fn greater_than_100() {
            Guess::new(200);
        }
    }
    ~~~
    - 실행 결과
    ~~~
    running 1 test
    test tests::greater_than_100 - should panic ... ok

    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
    ~~~
    - 버그 케이스 실행해보기 
    ~~~
    impl Guess {
        pub fn new(value: i32) -> Guess {
            if value < 1 {
                panic!("Guess value must be between 1 and 100, got {}", value);
            }

            Guess {value}
        }
    }
    ~~~
    - 실행 결과
    ~~~
    running 1 test
    test tests::greater_than_100 - should panic ... FAILED

    failures:

    ---- tests::greater_than_100 stdout ----
    note: test did not panic as expected

    failures:
        tests::greater_than_100

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
    ~~~
    - greater_than_100 테스트 함수는 `#[should_panic]`으로 애너테이션된 함수로 패닉이 발생하지 않아서 실패한 것이다
    - should_panic 테스트는 의도한 것과는 다른 이유로 패닉이 발생하는 경우가 있을 수 있기 때문에 정확하지 않을 수 있다
    - expected 매개변수를 추가해 포함되어야 하는 실패 메시지를 지정하면 더 꼼꼼한 should_panic 테스트를 작성할 수 있다   <br/><br/>
    - 특정한 부분 문자열을 포함하는 패닉 메시지를 사용한 panic! 테스트
    ~~~
    pub struct Guess {
        value: i32,
    }

    impl Guess {
        pub fn new(value: i32) -> Guess {
            if value < 1 {
                panic!("Guess value must be greater than or qual to 1, got {}", value);
            } else if value > 100 {
                panic!("Guess value must be less than or equal to 100, got {}", value);
            }

            Guess {value}
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        #[should_panic(expected = "less than or equal to 100")]
        fn greater_than_100() {
            Guess::new(200);
        }
    }
    ~~~
    - should_panic 속성의 expected 매개변숫값이 Guess::new 함수에서 발생한 패닉 메시지 문자열의 일부이므로 테스트는 통과한다   <br/><br/>
    - 버그 케이스 실행해보기
    ~~~
    impl Guess {
        pub fn new(value: i32) -> Guess {
            if value < 1 {
                panic!("Guess value must be less than or equal to 100, got {}", value);
            } else if value > 100 {
                panic!("Guess value must be greater than or qual to 1, got {}", value);
            }

            Guess {value}
        }
    }
    ~~~
    - 실행 결과
    ~~~
    running 1 test
    test tests::greater_than_100 - should panic ... FAILED

    failures:

    ---- tests::greater_than_100 stdout ----
    thread 'tests::greater_than_100' panicked at src/lib.rs:12:13:
    Guess value must be greater than or qual to 1, got 200
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    note: panic did not contain expected string
        panic message: `"Guess value must be greater than or qual to 1, got 200"`,
    expected substring: `"less than or equal to 100"`

    failures:
        tests::greater_than_100

    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
    ~~~
    - 테스트에서 패닉이 발생했지만 `"less than or equal to 100"` 문자열이 패닉 메시지에 포함되어 있지 않다는 것을 알려준다 
    - 패닉 메시지를 단서로 버그를 찾아낼 수 있다   <br/><br/>
- Result\<T,E>를 이용한 테스트
    - Result\<T,E>를 사용하여 패닉을 발생시키는 대신 Err을 반환한다
    - 테스트 함수 
        ~~~
        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn it_works() -> Result<(), String> {
                if 2+2 == 4{
                    Ok(())
                } else {
                    Err(String::from("two plus two does not equal four"))
                }
            }
        }
        ~~~
        - it_works 함수는 Result<(), String> 타입을 반환한다
        - assert_eq! 매크로를 호출하는 대신, 테스트 성공 시에는 Ok(())를 반환하고 실패 시에는 String을 갖는 Err을 반환한다
        - Result\<T,E>를 반환하는 테스트에서는 ? 연산자를 사용할 수 있기 때문에, 내부 작업이 Err를 반환할 경우 실패해야 하는 테스트를 작성하기 편리하다
        - `#[should_panic]` 애너테이션을 사용할 수 없다
        - Err 배리언트를 반환하는 것을 단언하기 위해서는 Result\<T,E> 값에 ? 연산자를 사용하지 말고 `assert!(value.is_err())`를 사용해야한다   <br/><br/>
### 테스트 실행 방법 제어하기
- cargo test 명령어는 코드를 테스트 모드에서 컴파일하고 생성된 바이너리를 실행한다
- cargo test에 의해 생성된 바이너리의 기본 동작은 모든 테스트를 병렬로 실행하고 테스트가 수행되는 동안 발생된 출력을 캡처하는 것으로, 출력이 표시되는 것을 막고 테스트 결과와 관련된 출력을 읽기 편하게 해준다
- 명령어 옵션은 cargo test에 전달되는 것도 있고, 테스트 바이너리에 전달되는 것도 있다   <br/><br/>
- 테스트를 병렬 혹은 순차적으로 실행하기
    - 여러 테스트를 실행할 때는 기본적으로 스레드를 사용해 병렬 실행된다 
    - 여러 테스트가 동시에 실행되므로, 각 테스트가 공유 사태를 갖거나 다른 테스트에 의존해서는 안 된다
    - 테스트를 병렬로 실행하고 싶지 않거나, 사용할 스레드의 개수에 대한 미세 조정이 필요한 경우에는 `--test-threads 플래그`를와 함께 테스트 바이너리에서 사용할 `스레드 개수`를 지정할 수 있다
        ~~~
        cargo test -- --test-threads=1
        ~~~
    - 스레드 개수를 1로 설정하먄 프로그램이 어떠한 병렬 처리도 사용하지 않도록 한다
    - 테스트 실행이 느려지지만, 서로 상태를 공유하는 테스트가 방해받을 일이 없다   <br/><br/>
- 함수 출력 표시하기 
    - 러스트 테스트 라이브러리는 성공한 테스트의 모든 표준 출력(standard output)을 캡처한다
    - 테스트가 성공하면 성공했다고 표시된 줄만 출력하고 실패하면 표준 출력으로 출력됐던 모든 내용이 실패 메시지 아래에 표시된다
    - println!을 호출하는 함수 테스트
        ~~~
        fn prints_and_returns_10(a: i32) -> i32 {
            println!("I got the value {}", a);
            10
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn this_test_will_pass() {
                let value = prints_and_returns_10(4);
                assert_eq!(10, value);
            }

            #[test]
            fn this_test_will_fail() {
                let value = prints_and_returns_10(8);
                assert_eq!(5, value);
            }
        }
        ~~~
        - 실행 결과
        ~~~
        running 2 tests
        test tests::this_test_will_pass ... ok
        test tests::this_test_will_fail ... FAILED

        failures:

        ---- tests::this_test_will_fail stdout ----
        I got the value 8
        thread 'tests::this_test_will_fail' panicked at src/lib.rs:19:9:
        assertion `left == right` failed
        left: 5
        right: 10
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


        failures:
            tests::this_test_will_fail

        test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - 성공한 테스트에서 출력했던 `I got the value 4`는 캡처되어 볼 수 없다
        - 실패한 테스트는 테스트 실패 원인과 함께 테스트 출력 요약 절에서 `I got the value 8`을 볼 수 있다
        - 성공한 테스트에서 출력한 내용도 보고 싶다면 `--show-output` 옵셥을 전달하면 된다
        ~~~
        cargo test -- --show-output
        ~~~
        - 실행 결과
        ~~~
        running 2 tests
        test tests::this_test_will_pass ... ok
        test tests::this_test_will_fail ... FAILED

        successes:

        ---- tests::this_test_will_pass stdout ----
        I got the value 4


        successes:
            tests::this_test_will_pass

        failures:

        ---- tests::this_test_will_fail stdout ----
        I got the value 8
        thread 'tests::this_test_will_fail' panicked at src/lib.rs:19:9:
        assertion `left == right` failed
        left: 5
        right: 10
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


        failures:
            tests::this_test_will_fail

        test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - successes 에 대한 출력 내용을 확인할 수 있다   <br/><br/>
- 이름을 지정해 일부 테스트만 실행하기
    - 세 가지 서로 다른 이름의 테스트 
        ~~~
        pub fn add_two(a: i32) -> i32 {
            a + 2
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn add_two_and_two() {
                assert_eq!(4, add_two(2));
            }

            #[test]
            fn add_three_and_two() {
                assert_eq!(5, add_two(3));
            }

            #[test]
            fn one_hundred() {
                assert_eq!(102, add_two(100));
            }
        }
        ~~~
        - `cargo test` 실행 결과
        ~~~
        running 3 tests
        test tests::add_three_and_two ... ok
        test tests::add_two_and_two ... ok
        test tests::one_hundred ... ok

        test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s   
        ~~~
    - **테스트 하나만 실행하기 - 테스트 함수 이름 전달**
        ~~~
        cargo test one_hundred
            Finished `test` profile [unoptimized + debuginfo] target(s) in 0.00s
             Running unittests src/lib.rs (target/debug/deps/add_two-2f4c3811eb6f8aba)

        running 1 test
        test tests::one_hundred ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s
        ~~~
        - one_hundred 테스트만 실행되고 나머지 두 테스트는 이름이 맞지 않아 실행되지 않는다
        - 2 filtered out을 표시하여 실헹한 테스트 외에 다른 테스트가 존재함을 알려준다   <br/><br/>
    - **테스트를 필터링하여 여러 테스트 실행하기**
        ~~~
        cargo test add 
            Finished `test` profile [unoptimized + debuginfo] target(s) in 0.00s
             Running unittests src/lib.rs (target/debug/deps/add_two-2f4c3811eb6f8aba)

        running 2 tests
        test tests::add_three_and_two ... ok
        test tests::add_two_and_two ... ok

        test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
        ~~~
        - 테스트 이름의 일부만 지정하면 해당 값에 맞는 모든 테스트가 실행된다
        - 테스트가 위치한 모듈도 테스트 이름의 일부로 나타나며 모듈 이름으로 필터링하면 해당 모듈 내 모든 테스트를 실행할 수있다   <br/><br/>
- 특별 요청이 없다면 일부 테스트 무시하기
    - 몇몇 특정 테스트는 오랜 시간이 걸려서 제외하고 싶을 때 igore 속성을 애너테이션하면 된다
    - 테스트 함수 작성 예시
        ~~~
        #[test]
        fn it_works() {
            assert_eq!(2+2, 4);
        }

        #[test]
        #[ignore]
        fn expensive_test() {
            // 실행오래 걸림
        }
        ~~~
        - 실행 결과
        ~~~
        cargo test
           Compiling adder v0.1.0 (/Users/byul/learning-rust/ch11/adder)
            Finished `test` profile [unoptimized + debuginfo] target(s) in 0.11s
             Running unittests src/lib.rs (target/debug/deps/adder-e11526392c9beffe)

        running 2 tests
        test tests::expensive_test ... ignored
        test tests::it_works ... ok

        test result: ok. 1 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - #[test] 다음 줄에 `#[ignore]` 줄을 추가하여 실행하면 expensive_test는 실행되지 않는다   <br/><br/>
    - 무시된 테스트만 실행하기 
        ~~~
        cargo test -- --ignored
            Finished `test` profile [unoptimized + debuginfo] target(s) in 0.00s
             Running unittests src/lib.rs (target/debug/deps/adder-e11526392c9beffe)

        running 1 test
        test tests::expensive_test ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
        ~~~
        - 무시한 테스트만 실행이 된다
    - ignore 속성을 애너테이션한 테스트 함수가 있더라도 모든 테스트를 실행하고 싶다면 ```cargo test --include-ignored```를 실행하면 된다   <br/><br/>
### 테스트 조직화
- 러스트 커뮤니티는 테스트를 크게 유닛 테스트(단위 테스트), 통합 테스트 두 종류로 나눈다
- 유닛 테스트(unit test)
    - 작고 집중적이다 
    - 한 번에 하나의 모듈만 테스트하며, 모듈의 비공개 인터페이스도 테스트할 수 있다
- 통합 테스트(integration test)
    - 완전히 라이브러리 외부에 위치하며, 외부 코드에서 사용할 때와 똑같은 방식을 사용한다
    - 하나의 테스트에서 잠재적으로 여러 모듈이 사용되기도 한다   <br/><br/>
- **유닛 테스트**
    - 각 코드 단위를 나머지 코드와 분리하여, 제대로 작동하지 않는 코드가 어느 부분인지 빠르게 파악하는 것이다
    - src 디렉터리 내의 각 파일에 테스트 대상이 될 코드와 함께 작성한다
    - 각 파일에 tests 모듈을 만들고 cfg(test)를 애너테이션하는 게 일반적인 관례이다   <br/><br/>
    - **테스트 모듈과 #[cfg(test)]**
        - `#[cfg(test)]`을 애너테이션 하는것은 cargo test 명령어 실행 시에만 컴파일 및 실행될 것이라는 점을 러스트에 전달한다
        - 통합 테스트는 별도의 디렉터리에 위치하기 때문에 애너테이션이 필요 없다
        - 유닛 테스트는 일반 코드와 같은 파일에 위치하기 때문에, #[cfg(test)] 애너테이션을 작성해 컴파일 결과물에 포함되지 않도록 명시해야 한다
        ~~~
        #[cfg(test)]
        mod tests {
            #[test]
            fn it_works() {
                assert_eq!(2+2, 4);
            }
        }
        ~~~
        - cfg 속성은 설정(configuration)을 의미하며, 이 아이템을 특정 설정 옵션 적용 시에만 포함한다
        - cfg 속서을 사용하면 카고는 cargo test 명령어를 실행할 때만 테스트 코드를 컴파일한다   <br/><br/>
    - 비공개 함수 테스트 하기
        ~~~
        pub fn add_two(a: i32) -> i32 {
            internal_adder(a, 2)
        }

        fn internal_adder(a: i32, b: i32) -> i32 {
            a + b
        }

        #[cfg(test)]
        mod tests {
            use super::*;

            #[test]
            fn internal() {
                assert_eq!(4, internal_adder(2,2));
            }
        }
        ~~~
        - 실행 결과
        ~~~
        running 1 test
        test tests::internal ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - 다른 언어에서는 비공개 함수를 테스트하기 어렵거나, 불가능하게 만들어 두었다
        - 러스트의 비공개 규칙은 비공개 함수를 테스트하도록 허용한다
        - `user super::*`를 사용하여 test 모듈의 부모에 있는 아이템을 모두 스코프 안으로 가져오고 internal_adder를 호출할 수 있다   <br/><br/>
- **통합 테스트**
    - 통합 테스트는 라이브러리와 완전히 분리되어 있다
    - 외부 코드와 마찬가지로, 공개 API만 호출 가능하다
    - 통합 테스트의 목적은 라이브러리의 여러 부분을 함께 사용했을 때 제대로 작동하는지 확인하는 것이다
    - 통합 테스트를 작성하려면 먼저 tests 디렉터리를 만들어야 한다   <br/><br/>
- tests 디렉터리
    - 프로젝트 디렉터리 최상위, src 옆에 tests 디렉터리를 생성한다
    - cargo는 디렉터리 내 통합 테스트 파일을 자동으로 인식한다
    - 비공개 함수 테스트하기의 파일이 작성된 프로젝트 디렉터리 최상위에 tests 디렉터리를 생성하고, tests/integration_test.rs 파일을 생성한다
        ~~~
        .
        ├── Cargo.lock
        ├── Cargo.toml
        ├── src
        │   └── lib.rs
        └── tests
            └── integration_test.rs
        ~~~
        - 위와 같은 디렉터리 구조를 보일 것이다
    - tests/integration_test.rs 코드 입력
        ~~~
        use internal;

        #[test]
        fn it_adds_two() {
            assert_eq!(4, internal::add_two(2));
        }
        ~~~
        - tests 디렉터리의 각 파일은 별개의 크레이트로, 각각의 테스트 크레이트의 스코프로 우리가 만든 라이브러리를 가져올 필요가 있다 (use adder을 추가한 이유)
        - cargo는 tests 디렉터리를 특별 취급하여, cargo test 시에만 컴파일 하기 때문에 #[cfg(test)] 를 입력하지 않아도 된다
        - 실행 결과
        ~~~
        cargo test
           Compiling internal v0.1.0 (/Users/byul/learning-rust/ch11/internal)
            Finished `test` profile [unoptimized + debuginfo] target(s) in 0.14s
             Running unittests src/lib.rs (target/debug/deps/internal-3f331a765625b00f)

        running 1 test
        test tests::internal ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

            Running tests/integration_test.rs (target/debug/deps/integration_test-72f82d1048be7664)

        running 1 test
        test it_adds_two ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

        Doc-tests internal

        running 0 tests

        test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - 출력에 유닛 테스트, 통합 테스트, 문서 테스트 세 가지 절이 만들어진다
        - 어떤 절 안에 어떠한 테스트라도 실패하면, 그다음 절은 실행되지 않는다
        - 통합 테스트 절은 `Running tests/`로 시작한다
        - 각각의 통합 테스트 파일은 별도의 출력 절을 생성하므로, tests 디렉터리에 파일을 추가하면 통합 테스트 절이 더 만들어질 것이다
        - 통합 테스트도 테스트 함수명을 인수로 전달해 특정 통합 테스트 함수를 실행할 수 있다
        - 특정 통합 테스트 파일의 모든 테스트를 실행하려면 `cargo test -- test file_name`을 입력하면 된다
            ~~~
            cargo test --test integration_test 
                Finished `test` profile [unoptimized + debuginfo] target(s) in 0.00s
                 Running tests/integration_test.rs (target/debug/deps/integration_test-72f82d1048be7664)

            running 1 test
            test it_adds_two ... ok

            test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
            ~~~
- **통합 테스트 내 서브 모듈**
    - 통합 테스트를 추가하다 보면, 조직화를 위해 tests 디렉터리에 더 많은 파일이 필요할 수도 있다
    - tests 내 각 파일은 각각의 크레이트로 컴파일되는데, 이는 각 통합 테스트 파일이 각각의 크레이트로 취급된다는 점 때문에 분리된 스코프를 만들어내는 데에는 유용하다
    - tests/common.rs 생성
        ~~~
        pub fn setup() {
            // 여기에 라이브러리 테스트와 관련된 설정 코드를 작성
        }
        ~~~
        - cargo test 실행 결과
        ~~~
        running 1 test
        test tests::internal ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

            Running tests/common.rs (target/debug/deps/common-5e93b1926e0b526a)

        running 0 tests

        test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

            Running tests/integration_test.rs (target/debug/deps/integration_test-72f82d1048be7664)

        running 1 test
        test it_adds_two ... ok

        test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

        Doc-tests internal

        running 0 tests

        test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
        ~~~
        - 결과 출력에 새로운 절이 common.rs 파일 때문에 생성된 것을 볼 수 있다
        - 결과 출력에서 common을 제외하려면 `tests/common.rs` 대신 `tests/common/mod.rs` 파일을 생성해야 한다
        - 디렉터리 구조
            ~~~
            ├── Cargo.lock
            ├── Cargo.toml
            ├── src
            │   └── lib.rs
            └── tests
                ├── common
                │   └── mod.rs
                └── integration_test.rs
            ~~~
            - 더 이상 테스트 결과 출력에 common이 나타나지 않는다
            - tests 디렉터리의 서브 디렉터리 내 파일은 별도 크레이트로 컴파일되지 않고 테스트 결과 출력에서 별도의 출력 절이 생성되지도 않는다
        - tests/common/mod.rs 파일을 생성하면 다른 통합 테스트 파일에서 모듈처럼 사용할 수 있다
        - setup 함수 호출 예시
            ~~~
            use internal;

            mod common;

            #[test]
            fn it_adds_two() {
                common::setup();
                assert_eq!(4, internal::add_two(2));
            }
            ~~~
- **바이너리 크레이트에서의 통합 테스트**
    - `src/lib.rs` 파일이 없고 `src/main.rs` 파일만 있는 바이너리 크레이트라면, tests 디렉터리에 통합 테스트를 만들어서 src/main.rs에 정의된 함수를 use 구문으로 가져올 수 없다
    - 다른 크레이트에서 사용할 수 있도록 함수를 노출하는 건 라이브러리 크레이트 뿐이다
    - 바이너리를 제공하는 러스트 프로젝트들이 src/main.rs 파일은 간단하게 작성하고, 로직은 src/lib.rs 파일에 위치시키는 이유 중 하나가 이 때문이다
    - 이런 구조로 작성하면 중요 기능을 통합 테스트에서 use 구문으로 가져와 테스트할 수 있다
    - 중요 기능이 제대로 작동하면 src/main.rs의 소량 코드도 작동할테니, 테스트하지 않아도 된다
    